name: docker-build-ascend-a3-qwen3_5

on:
  workflow_dispatch:

jobs:
  build-ascend-image-a3:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'verl-project' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-ascend-image-a3
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Remove unnecessary parts in github actions runners to free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Clean Docker cache before build
        run: |
          docker system prune -a -f --volumes || true

      - name: Build and push v0.8.0 image to Quay
        # if: ${{ github.event_name == 'schedule' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./docker/ascend/Dockerfile.ascend_8.5.1_a3_qwen3-5
          push: true
          tags: |
            quay.io/ascend/verl:verl-8.5.1-a3-ubuntu22.04-py3.11-qwen3-5
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
